const teamMembers = [
  {
    id: 1,
    groupName: '網站更新組',
    personNames: [
      '王◯恆',
      'Sam',
      'Zack',
      'JessZhong',
      'audery1011',
      'Pink Li',
      '施宇',
      'ppqq',
      '強森',
      'Yukay ',
      '破破popo',
      '彭◯珍',
      'WilliamTai',
      '陳◯妏',
      'Abby Su',
      'Wenny Chang',
      'Yi',
      '謝◯雯',
      'Stephanie Sung',
      'Sucre Lin 林糖糖',
      'IKEA',
      'jerry._.',
      'Randy',
      'cy.hsu',
      'Sylvia Kuo',
      '陳◯柔',
      'JeanLu',
      'BensonTW',
      'ZhuMon',
      'Arey',
      'Ava Tu',
      'Mizhon',
      'Pichu',
      'haoyun, shih',
      '蘇◯育',
      'Glori',
      'Lindsay',
      'Meeka',
      'Oswald',
      'DanLin',
      'Chi',
      'Carol 朱◯綾',
      '浩富',
    ],
  },
  {
    id: 2,
    groupName: '宣傳組',
    personNames: [
      '于涵',
      'Sunny Yang',
      '捲捲 FANG JOU',
      '小魏 WEI',
      'ヨウヨウ',
      'Julia(小孟)',
      '阿一',
    ],
  },
  {
    id: 3,
    groupName: '地圖組',
    personNames: [
      'Zack',
      'Fannie',
      '張◯瑜',
      '雅',
      'Zeli',
      '曾◯容 (鷹)',
      'Claire',
      'ShunFa Yang',
      '嵐',
      'billy',
    ],
  },
  {
    id: 4,
    groupName: '設計組',
    personNames: [
      'Vita',
      'Sunny Yang',
      '葉◯均 Andy',
      'JessZhong',
      '瑜瑜',
      'Pichu',
      'Yuling',
      '渺渺',
      'Sucre Lin 林糖糖',
      'Doublewen',
    ],
  },
  {
    id: 5,
    groupName: 'DC管理組',
    personNames: ['JessZhong', 'Sunny Yang', '瑜瑜', 'Tobie 偷偷', 'Andrew Yen', 'Chun Caroline'],
  },
  {
    id: 6,
    groupName: 'Line社群組 & 官方組',
    personNames: ['于涵', '施宇 (鯊魚)'],
  },
  {
    id: 7,
    groupName: '廣宣組',
    personNames: ['Sunny Yang', 'Jocelyn', 'Yukay', 'Andrew Yen', 'Julia (小孟)'],
  },
  {
    id: 8,
    groupName: '核實組',
    personNames: ['雅', '嵐', '小路'],
  },
  {
    id: 9,
    groupName: '公關組',
    personNames: ['捲捲 FANG JOU', 'Andrew Yen'],
  },
  {
    id: 10,
    groupName: '海巡組',
    personNames: ['Janet', '嵐', '小路', '艾瑪', 'DanLin', '出包'],
  },
  {
    id: 11,
    groupName: '進度管理組',
    personNames: ['Sucre Lin 林糖糖', 'Aylin'],
  },
];

export { teamMembers };
